sudo: false
language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
branches:
  only:
    - master
    - dev
    - /^dev\-.*$/
script:
  - ./scripts/build.sh
notifications:
  email: false
